services:
  xm-manager:
    image: openjdk:8-jdk-alpine
    volumes:
      - ./server/target/ruoyi-admin.jar:/app/app.jar
      - tmp


  xm-nginx:
#    restart: on-failure
    image: nginx:alpine
    ports:
      - ${NGINX_PORT:-80}:80   # Disable this if you are using TLS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/www/:/opt/www/
      - ./nginx/manager/:/opt/manager/